### ISSUE TITLE
启动快捷键

### ISSUE THREAD

**Issue by SSSDNSY** [hegelsu/SuWar3Tools#10]
我们用过wegame，魔兽大脚之类的，建议加个启动魔兽的快捷键，或者快捷图标，目前只能托盘图标设置 和设置启动，感觉不是很爽呢。。。望作者加一下，感谢开源分享~YYDS

**Comment by SSSDNSY** [comment]
就是启动这个工具之后，我们可以用一键启动或者快捷键启动魔兽，节省用户操作

**Comment by hegelsu** [comment]
![123](https://user-images.githubusercontent.com/6879123/187013494-93da044e-c316-4a33-8c2b-f3cb54599266.png)
暂时可以如上图设置，启动本软件同时也会启动魔兽

**Comment by SSSDNSY** [comment]
还是希望能加个一键启动 或者快捷键 哈哈哈

**Comment by hegelsu** [comment]
> 还是希望能加个一键启动 或者快捷键 哈哈哈
最新版在“临时开关”上右键可以设置启动快捷键
