### ISSUE TITLE
希望作者可以开发一个战绩统计以及激活发球开关的热键

### ISSUE THREAD

**Issue by huiyuhuiyi** [hegelsu/SuWar3Tools#11]
作者你好, dota 里面有很多英雄带发球, 譬如 小鹿的T, 毒龙的1技能, 沉默的智慧之刃, 往往中期很多时候被对面隐身偷袭, 或者打团, 需要及时右键激活这类发球技能 变为自动施法, 而这个过程起码会浪费0.5-1秒时间, 这个过程角色可能还会使用普通攻击而不是施展发球, 这样就导致不能及时打出伤害, 如果作者可以开发到一个 自定义热键的 发球技能激活开关, 通过热键激活发球自动施法, 而不是鼠标右键激活, 这么我想象,这个功能属于压轴性的功能 , 

另外作者可否开发一个本地存储的战绩统计, 譬如进入游戏后, 显示本地文本记录是玩的第几把游戏, 类象这种功能, 摆脱平台账号的约束

**Comment by hegelsu** [comment]
![1](https://user-images.githubusercontent.com/6879123/236620255-28675171-9baa-4155-9d99-aabb6cc9807d.png)

自动右键的可以这样去设置哈。

统计的就弄不了了，这至少得一个团队，目前个人精力和时间无法处理这个哈。

**Comment by huiyuhuiyi** [comment]
谢谢作者回复, 这个功能我很早很早就试过了, 就是延迟不好用, 如果手速快还会打断的,



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月6日(星期六) 晚上7:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hegelsu/SuWar3Tools] 希望作者可以开发一个战绩统计以及激活发球开关的热键 (Issue #11)





 

 
自动右键的可以这样去设置哈。
 
统计的就弄不了了，这至少得一个团队，目前个人精力和时间无法处理这个哈。

**Comment by hegelsu** [comment]
是的，本身右键点击激活魔兽就没有快捷键，所以我这边只能采用鼠标的方式进行模拟，目前我这边没有其它更快的办法了，但我所知的是可以注入魔兽调用相关的函数来处理这块，但这个个人能力有限，而且魔兽版本众多，要适配也是个不小的工作。
