### ISSUE TITLE
启用"强制改键于未支持的魔兽"会使得改键影响打字

### ISSUE THREAD

**Issue by Surgeol** [hegelsu/SuWar3Tools#14]
如标题所描述，不知道这是否算是一个bug，我测试的魔兽版本为最新虫蛀版。
当然不启用该选项还是正常使用的，如果这是一个无法解决的问题，不妨考虑添加一行tooltips说明一下？

**Comment by hegelsu** [comment]
这个不是Bug的，强制改键于未支持的魔兽的使用情况是比较少的，这个选项使用的情况是魔兽版本是第三方修改过了，比如1.24的版本魔兽，正常上改键是正常的，但有些平台或是个人会在此版本上对魔兽程序做一些特殊修改，可能导致原来的改键功能不可用了，所以就会有这一个选项，此选项至少会保证改键是可用的，但会对聊天有影响，因为程序已经无法正常对修改过的魔兽判断来判断是否聊天状态了，所以就出现上述你说的现像。tip的我后面可以加一下哈。

**Comment by hegelsu** [comment]
参考： https://github.com/hegelsu/SuWar3Tools/issues/15
