### ISSUE TITLE
重制版1.35破解没法使用改键工具

### ISSUE THREAD

**Issue by LiHangMaiK** [hegelsu/SuWar3Tools#15]
大佬好，目前暴雪国服已经没了，但是网上还是有1.35的离线破解版，我下载了1.35，外加破解补丁，发现suWar3Tools不起作用了~也不知道为啥，老的单机魔兽1.20还可以正常使用这个改键工具~，如果大佬有空，可以看下

**Comment by MoonDemon** [comment]
你能分享一下1.35的离线破解版，外加破解补丁吗？

请参考下图，我在1.32可以使用
![image](https://user-images.githubusercontent.com/47078111/235033341-e57669e3-dd79-437f-bd04-8693fbd4c340.png)

**Comment by LiHangMaiK** [comment]
> 你能分享一下1.35的离线破解版，外加破解补丁吗？
> 
> 请参考下图，我在1.32可以使用 ![image](https://user-images.githubusercontent.com/47078111/235033341-e57669e3-dd79-437f-bd04-8693fbd4c340.png)



我也是你这样设置的，方案没有打勾，右边也是这样勾选的，点击了开启改键，但是游戏里不行。

1.35离线破解版我是在BiliBili的这位up主视频简介里下载的，应该是官方的1.35，外加破解文件。
https://www.bilibili.com/video/BV1o54y1P7Ls/
目前依然能下载~

简介里分享的是迅雷的云盘，按照破解文件内的Readme文档操作后就可以本地离线玩单机了。
但是就是不能改键，之前魔兽重制版国服还没有关闭的时候，我也能使用这个工具改键。
或许是我下载错了版本？


如果不介意的话，能分享你的魔兽重制版1.32版本么？因为我只玩单机，1.32和1.35也没区别~

**Comment by MoonDemon** [comment]
我是网易关闭之后我的1.32也不能玩了，所以我才问你要1.35的破解

**Comment by LiHangMaiK** [comment]
你有1.32，你应该可以直接下载破解文件，找到网易那个自带的魔兽3重制版目录覆盖，然后按操作添加注册表，就能玩了，需要注意的是，选项设置里改成经典版的，哎，我下载这个1.35版改不了键。。好烦~

**Comment by MoonDemon** [comment]
好的，谢谢

**Comment by hegelsu** [comment]
针对改键不起作用的时候，可以尝试以下两种方式
第一种：勾选“强制改键于未支持的魔兽”，在全局设置右边的箭头里设置
![1](https://user-images.githubusercontent.com/6879123/236621191-18794d71-abe3-472d-8568-0764f7a4c2b7.png)
此种设置方式会影响聊天打字
第二种：设置聊天判断点：
![1](https://user-images.githubusercontent.com/6879123/236621297-e332a0a2-8626-4781-a136-00bbbdd2ff2b.png)
获取判断点示例：
![1](https://user-images.githubusercontent.com/6879123/236621333-a6bcb366-4712-48ee-8373-62849cd37b26.png)
以上两种方式任选一种即可。
