### ISSUE TITLE
【按下 改为】 功能

### ISSUE THREAD

**Issue by Crzq** [hegelsu/SuWar3Tools#16]
【按下 改为】这个自定义改键功能4个我觉得不够用。是这样的，我在魔兽重置版中玩DOTA土猫这个英雄，由于技能改键没有用，只有背包生效了，我就想着用自定义改键，但是土猫有4个技能+1个放石头，要用到5个键，这就不够用了。而我又想到小精灵这个英雄（我也经常玩）有4个技能+拉近/拉远（二技能），要用到六个键。所以我恳请作者再加几个自定义改建，或者这个数量能让我们自己决定。

在写完上面的时候，我又想到【一改多】有3个，但我觉得大材小用，所以还是像上面说的。在更新之前，我就借用一下【一改多】吧。

**Comment by hegelsu** [comment]
【按下 改为】这里没有位置了，如果有超过4个的，其实你可以在【一改多】右边的箭头点一下会发现有10个可以快速录入的，=号左边的就是按下，=号右边的就是改为
