### ISSUE TITLE
最新的版本的背包改建问题

### ISSUE THREAD

**Issue by q19484** [hegelsu/SuWar3Tools#18]
主界面的背包修改不了改建了 点击保存直接就是qweasd我一般设置的是alt+qweasd 只能在其他里面修改 上个版本还好好的 不过上个版本没有快捷施法   增加的鼠标左键功能挺好用的 就是改建保存不了也用不了

**Comment by hegelsu** [comment]
已修正

**Comment by q19484** [comment]
感谢大哥
