### ISSUE TITLE
组合按键问题

### ISSUE THREAD

**Issue by aaaaasuper** [hegelsu/SuWar3Tools#5]
![组合按键](https://user-images.githubusercontent.com/10217680/123806907-f905ff00-d921-11eb-8cbf-a62427ff1de3.png)
组合按键现在有点问题：
1.ALT+E 改成一个连续按键时候，按住不松开不会一直触发按键，就是只会触发一次，其他改建软件是可以的。
ALT+其他按键都是这样，希望增加这个功能。

2.SHIFT+R 改成连续按键的时候，按住不松开会一直触发，但是Shift键没有抬起，Shfit是一直按下去的，单位的动作都变成按住Shift的效果了，地面上会有一个旗帜，其他改建工具不会这样，希望可以弹起Shift。

3.希望增加自动开启改建功能，魔兽切换的时候改建就不生效了，需要按快捷键。

**Comment by hegelsu** [comment]
我这边测试1和2都是只触发一次，目前程序增加了右键菜单“保持功能组合键状态“，请更新到最新版尝试看是否解决你的问题。
第3点在开启改键状态默认是只对魔兽生效的，切出魔兽再切回来改键仍然是生效的，如非此情况还请详细说明操作时的情况。
