### ISSUE TITLE
小键盘 hero only 问题

### ISSUE THREAD

**Issue by cc20002002** [hegelsu/SuWar3Tools#6]
我把我的小键盘4改成了V键。在网易里这样改是不影响V键的其他使用的，比如说我可以同时用农民造人族商店（快捷键BV）。然后suwar3tools 设置了小键盘4为V键 其他单位的快捷键V就失效了。这个问题有办法吗？

**Comment by hegelsu** [comment]
鼠标放在将“小键盘4”上可看到提示，点成绿色或橙色即可
