### ISSUE TITLE
146版本更新的bug问题建议

### ISSUE THREAD

**Issue by 1102554795** [hegelsu/SuWar3Tools#7]
这次的更新内容我有点看不懂，不过这并妨碍我去使用，然而在使用时立马就发现了之前能用的更新后不能用了。这还是第一次出现更新后的不如更新前的。具体问题如下：
魔兽改键器一直没有多种喊话方案，也就是我要针对不同的地图设置不同的喊话方案，就像不同的改键方案一样。为此，我自己利用高级改键这一功能，通过另一个角度实现了多种喊话方案这一功能，当然有不足。

正常比如我们设置ALT+1是喊话“HG”，但是如果我们玩另外一张魔兽地图，要把ALT+1喊话变成”我要回城“，这样我们就不得不临时更改喊话，很麻烦，对不对？所以我就吧ALT+7设置成”HG“，然后在高级改键里面设置按下ALT+1改为ALT+7,这样即使ALT+1里面是空的也可以通过按ALT+1喊话出”HG“。然后我们吧ALT+8设置成”我要回城“，在另外一张地图的改键方案里，在高级改键里在设置按ALT+1改为ALT+8，同样ALT+1也是空的，这样一来，在这个方案里我们按ALT+1就会喊话出”我要回城“。
通过这种繁琐的方式，我实现了多种喊话方案这一功能。这样在玩不同地图的时候只需要切换方案就可以了，而不必每次都临时更改喊话内容。

但是。。。。。。。。
这次的更新我发现我之前设置的这个不能用了，我必须要按alt+7才能喊话”HG“，就是不能通过喊话喊另一喊话，我也不能再高级改键里设置按ALT+1改为ALT+1 ALT+2 ALT+3 ALT+4.。。。这种只按一下ALT+1就能将所有喊话都喊一遍。
简单一句话，更新后不知道是延迟了还是什么别的问题，我不能用我设计的这一套”多方案喊话“功能了。
特此建议：
1、取消强制更新，添加以往版本下载，我想用回以前的版本，那样就挺好的了。
2、建议设计出”多方案喊话“这一功能，就像改键有多方案一样，每个地图都有不同的喊话。目前为止我没见过任何改建，任何平台有”多方案喊话“这一功能。上面的迂回路线也是我自己利用高级改键实现的。
额外建议：
添加显示蓝条功能，这个功能在很多平台就有了，不知道为啥改建器却只有显示血条，而没有显示蓝条，可能技术层面真的很难吧。
急急急！！！此次更新很无语。。。。

**Comment by hegelsu** [comment]
实在抱歉，现在才抽点时间来更新下，增加了多喊话方案的功能，感谢支持。
显蓝的功能个人能力有限，请先使用其它工具的显蓝功能配合使用。
