### ISSUE TITLE
关于英雄选中的问题

### ISSUE THREAD

**Issue by yedongyu1996** [hegelsu/SuWar3Tools#8]
dota玩家
我将F1键设置为空格，用空格来选中自己
但是当我给小鸡编号5，选中小鸡，再按空格键后，之前的F1改键失效

**Comment by hegelsu** [comment]
请确保是否勾选了方案右边的“改键只对英雄有效”的选项，如果勾选后可能会导致上面的结果，小鸡会被识别为非英雄单位，所以改键不生效，可以在高级里添加F1改空格的设置并在F1上右键选择“选选了英雄有效果非英雄也生效”的选项即可，
