### ISSUE TITLE
界面中文字体乱码

### ISSUE THREAD

**Issue by foluie** [hegelsu/SuWar3Tools#9]
软件功能挺全挺好的，就是软件界面中文字体经常乱码，怎么解决？

**Comment by hegelsu** [comment]
![123](https://user-images.githubusercontent.com/6879123/187013268-fdabb214-1576-4410-8798-311fe5b16dbe.png)
由于一些平台会主动杀掉改键工具，判断方法是检测软件界面上的文本是否包含“魔兽”等字眼，有就给你关掉，所以在这里有做改变，以防止某些平台关掉此工具。
